version: '3'
services:
  core:
    build:
      context: .
      args:
        # please edit VIVADO_TAR_HOST=HOST:PORT 
        - VIVADO_TAR_HOST=172.18.0.1:80
        - VIVADO_TAR_FILE=Xilinx_Vivado_SDK_2017.4_1216_1
        - VIVADO_VERSION=2017.4
    tty: true
    stdin_open: true
