version: '3'
services:
  core:
    build:
      context: .
      args:
        # please edit VIVADO_TAR_HOST=HOST:PORT
        - VIVADO_TAR_HOST=172.18.0.1:80
        - VIVADO_TAR_FILE=Xilinx_Vivado_SDK_2018.1_0405_1
        - VIVADO_VERSION=2018.1
    tty: true
    stdin_open: true
    privileged: true
    #environment:
    # - DISPLAY=$DISPLAY
    # for debug vivado
    cap_add:
      - ALL
    volumes:
      - datastore:/home/vivado/workspace
      - /dev/ttyUSB1:/dev/ttyUSB1
    ports:
      - "2223:22"
        #    entrypoint:
        # - /usr/sbin/sshd
        # - D
    entrypoint:
      - entrypoint

volumes:
  datastore:
