version: '3'
services:
  core:
    build:
      context: .
      args:
        # please edit VIVADO_TAR_HOST=HOST:PORT
        - VIVADO_TAR_HOST=172.18.0.1:80
        - VIVADO_TAR_FILE=Xilinx_Vivado_SDK_2018.1_0405_1
        - VIVADO_VERSION=2018.1
          #privileged: true
    # for debug vivado
    #tty: true
    #stdin_open: true
    cap_add:
      - sys_admin
    volumes:
      - datastore:/home/vivado/workspace
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    ports:
      - "2223:22"
    entrypoint:
      - entrypoint

volumes:
  datastore:
